export type Product = {
  id: number;
  name: string;
  highlight: string;
  image: string;
  price: number;
  originalPrice: number;
  rating: number;
  reviewCount: number;
  bullets?: string[];
  category: string;
  subcategory: string;
};

export type BeautyService = {
  id: number;
  category: string;
  parlourName: string;
  location: string;
  address: string;
  phone: string;
  workingHours: string;
  serviceName: string;
  image: string;
  startingPrice: number;
  servicesOffered: string[];
  /** Optional descriptions for each service (same order as servicesOffered). */
  serviceDescriptions?: string[];
  /** Optional video URL for location/parlour preview (autoplay on details page). */
  videoUrl?: string;
};

export const products: Product[] = [
  { id: 1, name: "True Beauty Day Cream", highlight: "Bright, fresh & hydrated skin all day", image: "/images/products/dayCream.png", price: 1299, originalPrice: 1699, rating: 4.8, reviewCount: 128, bullets: ["SPF-enriched day protection", "Lightweight, non-greasy formula", "Suitable for all skin types", "Dermatologist tested"], category: "skincare", subcategory: "moisturizers" },
  { id: 2, name: "True Beauty Night Cream", highlight: "Repair & nourish while you sleep", image: "/images/products/nightCream.png", price: 1399, originalPrice: 1799, rating: 4.9, reviewCount: 94, bullets: ["Deep repair & regeneration", "Rich, nourishing texture", "Reduces fine lines overnight", "Free from parabens"], category: "skincare", subcategory: "moisturizers" },
  { id: 3, name: "True Beauty Sunscreen", highlight: "Broad spectrum SPF protection", image: "/images/products/sunscreen.png", price: 1199, originalPrice: 1599, rating: 4.7, reviewCount: 156, bullets: ["Broad spectrum SPF 50+", "Water-resistant formula", "No white cast", "Reef-safe & cruelty-free"], category: "skincare", subcategory: "sunscreen" },
  { id: 4, name: "True Beauty Face Wash", highlight: "Gentle cleanser for radiant skin", image: "/images/products/faceWash.png", price: 999, originalPrice: 1399, rating: 4.6, reviewCount: 203, bullets: ["Gentle, pH-balanced formula", "Removes dirt & makeup", "Does not strip natural oils", "With natural extracts"], category: "skincare", subcategory: "cleansers" },
  { id: 5, name: "True Beauty Serum", highlight: "Intensive hydration & glow", image: "/images/products/serum.png", price: 1499, originalPrice: 1899, rating: 4.9, reviewCount: 87, bullets: ["Concentrated active ingredients", "Visible glow in days", "Fast-absorbing, lightweight", "Vitamin C & hyaluronic acid"], category: "skincare", subcategory: "serums" },
  { id: 6, name: "True Beauty Moisturizer", highlight: "24-hour lasting hydration", image: "/images/products/moisturizer.png", price: 1399, originalPrice: 1799, rating: 4.7, reviewCount: 112, bullets: ["Long-lasting 24h hydration", "Strengthens skin barrier", "Non-comedogenic", "For day & night use"], category: "skincare", subcategory: "moisturizers" },
  { id: 7, name: "True Beauty Toner", highlight: "Balance & refine pores", image: "/images/products/toner.png", price: 1099, originalPrice: 1499, rating: 4.5, reviewCount: 76, bullets: ["Balances skin pH", "Refines pores & texture", "Prepares skin for serums", "Alcohol-free formula"], category: "skincare", subcategory: "toners" },
  { id: 8, name: "True Beauty Face Mask", highlight: "Deep detox & brightening", image: "/images/products/faceMask.png", price: 1199, originalPrice: 1599, rating: 4.8, reviewCount: 145, bullets: ["Deep cleansing clay base", "Removes impurities", "Brightens & evens tone", "Use 1–2 times a week"], category: "skincare", subcategory: "masks" },
  { id: 9, name: "True Beauty Lip Balm", highlight: "Nourishing moisture for lips", image: "/images/products/lipBalm.png", price: 999, originalPrice: 1299, rating: 4.9, reviewCount: 234, bullets: ["Long-lasting moisture", "Natural oils & shea butter", "SPF protection", "No fragrance irritation"], category: "skincare", subcategory: "moisturizers" },
  { id: 10, name: "Classic Pearl Studs", highlight: "Elegant sterling silver with pearl", image: "/categories/jewellery/jewellery1.png", price: 899, originalPrice: 1199, rating: 4.8, reviewCount: 42, bullets: ["Sterling silver", "Freshwater pearl", "Hypoallergenic", "Elegant everyday wear"], category: "jewellery", subcategory: "earrings" },
  { id: 11, name: "Rose Gold Pendant", highlight: "Minimalist pendant for everyday wear", image: "/categories/jewellery/jewellery2.png", price: 1499, originalPrice: 1999, rating: 4.9, reviewCount: 28, bullets: ["Rose gold plated", "Delicate chain", "Layering piece", "Gift box included"], category: "jewellery", subcategory: "pendants" },
  { id: 32, name: "True Beauty Statement Ring", highlight: "Bold ring for a polished look", image: "/categories/jewellery/jewellery3.png", price: 1999, originalPrice: 2499, rating: 4.7, reviewCount: 58, bullets: ["Premium finish", "Comfort fit", "Statement design", "Hallmarked"], category: "jewellery", subcategory: "rings" },
  { id: 12, name: "True Beauty Foundation & Glow", highlight: "Buildable coverage with a natural finish", image: "/categories/makeup/makeup1.png", price: 1599, originalPrice: 1999, rating: 4.8, reviewCount: 89, bullets: ["Lightweight, buildable coverage", "SPF-enriched formula", "Suitable for all skin types", "Long-lasting wear"], category: "makeup", subcategory: "foundation" },
  { id: 13, name: "True Beauty Lip & Cheek Palette", highlight: "Multipurpose shades for lips and cheeks", image: "/categories/makeup/makeup2.png", price: 1299, originalPrice: 1699, rating: 4.7, reviewCount: 64, bullets: ["Creamy, blendable formula", "8 versatile shades", "Long-wearing, transfer-resistant", "Compact for on-the-go"], category: "makeup", subcategory: "lips" },
  { id: 14, name: "True Beauty Eyeshadow Palette", highlight: "Matte and shimmer shades for every look", image: "/categories/makeup/makeup3.png", price: 1499, originalPrice: 1899, rating: 4.9, reviewCount: 112, bullets: ["12 highly pigmented shades", "Blendable matte & shimmer", "Cruelty-free & vegan", "Travel-friendly mirror palette"], category: "makeup", subcategory: "eyes" },
  { id: 15, name: "True Beauty Body Wash", highlight: "Refreshing cleanse with natural extracts", image: "/categories/bath&body/bodyWash.png", price: 799, originalPrice: 999, rating: 4.7, reviewCount: 156, bullets: ["Gentle, pH-balanced formula", "Long-lasting fragrance", "Moisturizing blend", "Suitable for daily use"], category: "bath-body", subcategory: "cleansers" },
  { id: 16, name: "True Beauty Body Lotion", highlight: "24h moisture for soft, smooth skin", image: "/categories/bath&body/bodyLotion.png", price: 999, originalPrice: 1299, rating: 4.8, reviewCount: 98, bullets: ["Fast-absorbing, non-greasy", "Enriched with shea butter", "All skin types", "Dermatologist tested"], category: "bath-body", subcategory: "moisturizers" },
  { id: 17, name: "True Beauty Body Scrub", highlight: "Exfoliate & reveal glowing skin", image: "/categories/bath&body/bodyScrub.png", price: 1099, originalPrice: 1399, rating: 4.9, reviewCount: 87, bullets: ["Natural exfoliating particles", "Nourishing oils", "Smooth, radiant skin", "Use 2–3 times a week"], category: "bath-body", subcategory: "scrubs" },
  { id: 18, name: "True Beauty Soap Bar", highlight: "Handcrafted, gentle cleansing bar", image: "/categories/bath&body/soapBar.png", price: 499, originalPrice: 699, rating: 4.6, reviewCount: 203, bullets: ["Natural ingredients", "Long-lasting bar", "Eco-friendly packaging", "Multiple fragrances"], category: "bath-body", subcategory: "cleansers" },
  { id: 19, name: "True Beauty Hair Shampoo", highlight: "Gentle cleanse for healthy, shiny hair", image: "/categories/hairCare/hairShampoo.png", price: 899, originalPrice: 1199, rating: 4.7, reviewCount: 134, bullets: ["Sulphate-free formula", "Nourishes from root to tip", "Suitable for all hair types", "Natural extracts"], category: "haircare", subcategory: "shampoos" },
  { id: 20, name: "True Beauty Hair Conditioner", highlight: "Deep conditioning for soft, manageable hair", image: "/categories/hairCare/hairConditioner.png", price: 949, originalPrice: 1249, rating: 4.8, reviewCount: 98, bullets: ["Detangles & smoothens", "Adds shine & bounce", "Repairs damaged ends", "Lightweight, non-greasy"], category: "haircare", subcategory: "conditioners" },
  { id: 21, name: "True Beauty Hair Oil", highlight: "Nourishing oil for stronger, longer hair", image: "/categories/hairCare/hairOil.png", price: 799, originalPrice: 999, rating: 4.9, reviewCount: 167, bullets: ["Cold-pressed natural oils", "Reduces hair fall", "Promotes growth", "Pre-wash & leave-in use"], category: "haircare", subcategory: "oils" },
  { id: 22, name: "True Beauty Perfume", highlight: "Signature scent for lasting elegance", image: "/categories/fragrance/perfume.png", price: 1899, originalPrice: 2399, rating: 4.8, reviewCount: 156, bullets: ["Long-lasting Eau de Parfum", "Premium fragrance notes", "Elegant bottle design", "Unisex appeal"], category: "fragrance", subcategory: "perfumes" },
  { id: 23, name: "True Beauty Body Mist", highlight: "Light, refreshing fragrance for all day", image: "/categories/fragrance/bodyMist.png", price: 699, originalPrice: 899, rating: 4.7, reviewCount: 203, bullets: ["Light, non-overpowering", "Perfect for layering", "Hydrating formula", "Multiple fragrances"], category: "fragrance", subcategory: "mists" },
  { id: 24, name: "True Beauty Roll-On Perfume", highlight: "Compact fragrance for on-the-go", image: "/categories/fragrance/roll-on.png", price: 599, originalPrice: 799, rating: 4.6, reviewCount: 98, bullets: ["Travel-friendly size", "Precise application", "Long-lasting scent", "Pocket-friendly"], category: "fragrance", subcategory: "roll-on" },
  { id: 25, name: "True Beauty Vitamins & Supplements", highlight: "Daily nutrition for skin, hair & wellness", image: "/categories/wellness/wellness1.png", price: 1299, originalPrice: 1599, rating: 4.8, reviewCount: 112, bullets: ["Skin & hair support", "Essential vitamins", "Easy-to-swallow", "30-day supply"], category: "wellness", subcategory: "vitamins" },
  { id: 26, name: "True Beauty Hair & Skin Gummies", highlight: "Tasty gummies for glow from within", image: "/categories/wellness/wellness2.png", price: 899, originalPrice: 1149, rating: 4.9, reviewCount: 234, bullets: ["Biotin & collagen", "Natural fruit flavours", "Sugar-free option", "2 gummies daily"], category: "wellness", subcategory: "gummies" },
  { id: 27, name: "True Beauty Herbal Teas", highlight: "Calming blends for mind & body", image: "/categories/wellness/wellness3.png", price: 599, originalPrice: 799, rating: 4.7, reviewCount: 87, bullets: ["Organic herbs", "Antioxidant-rich", "Caffeine-free options", "Gift-ready packaging"], category: "wellness", subcategory: "teas" },
  { id: 28, name: "True Beauty Wellness Kit", highlight: "Complete self-care in one box", image: "/categories/wellness/wellness4.png", price: 2499, originalPrice: 3199, rating: 4.8, reviewCount: 64, bullets: ["Curated essentials", "Vitamins + teas + gummies", "Travel pouch included", "Perfect gifting"], category: "wellness", subcategory: "kits" },
  { id: 29, name: "True Beauty Skincare Gift Set", highlight: "Curated skincare essentials in a beautiful box", image: "/categories/gifting/gift1.png", price: 2999, originalPrice: 3699, rating: 4.9, reviewCount: 89, bullets: ["Best-selling minis", "Elegant gift packaging", "For all skin types", "Message card included"], category: "gifting", subcategory: "skincare-sets" },
  { id: 30, name: "True Beauty Luxury Gift Box", highlight: "Premium collection for someone special", image: "/categories/gifting/gift2.png", price: 4999, originalPrice: 5999, rating: 4.8, reviewCount: 56, bullets: ["Luxury packaging", "Full-size favourites", "Ribbon & personalisation", "Ideal for gifting"], category: "gifting", subcategory: "luxury-boxes" },
  { id: 31, name: "True Beauty Personalized Gift", highlight: "Customised gift set with a personal touch", image: "/categories/gifting/gift3.png", price: 3499, originalPrice: 4299, rating: 4.9, reviewCount: 72, bullets: ["Name or message engraving", "Curated to recipient", "Gift wrap & card", "Same-day dispatch"], category: "gifting", subcategory: "personalized" },
  { id: 33, name: "Flash Sale – Skincare Duo", highlight: "Limited-time deal on bestsellers", image: "/categories/offers/offer1.png", price: 1999, originalPrice: 2999, rating: 4.8, reviewCount: 156, bullets: ["Day Cream + Serum combo", "Up to 33% off", "Limited stock", "Free shipping"], category: "offers", subcategory: "flash-sales" },
  { id: 34, name: "Buy 1 Get 1 – Lip & Cheek", highlight: "Get one free on select makeup", image: "/categories/offers/offer2.png", price: 1299, originalPrice: 2598, rating: 4.9, reviewCount: 89, bullets: ["BOGO on lip & cheek palette", "Same or lower value", "All shades included", "Valid this week"], category: "offers", subcategory: "bogo" },
  { id: 35, name: "New Arrivals Sale – Wellness", highlight: "Fresh drops at special price", image: "/categories/offers/offer3.png", price: 999, originalPrice: 1299, rating: 4.7, reviewCount: 64, bullets: ["New vitamins & gummies", "Launch discount", "Limited period", "Early access"], category: "offers", subcategory: "new-arrivals" },
  { id: 37, name: "Combo Offer – Full Routine", highlight: "Complete regimen in one bundle", image: "/categories/offers/offer5.png", price: 4499, originalPrice: 5999, rating: 4.8, reviewCount: 78, bullets: ["Cleanser + serum + moisturizer", "Save 25%", "Gift pouch included", "Best for beginners"], category: "offers", subcategory: "combo" },
];

export const beautyServices: BeautyService[] = [
  { id: 1, category: 'skincare', parlourName: 'Glow & Grace Skin Studio', location: 'Andheri West, Mumbai', address: '2nd Floor, Pearl Plaza, SV Road, Andheri West, Mumbai, Maharashtra 400058', phone: '+91 98765 12345', workingHours: '10:00 AM – 8:00 PM (Mon–Sun)', serviceName: 'Hydra Glow Facial', image: '/services/bath&body/hydraFacial.png', startingPrice: 1499, servicesOffered: ['Hydra Facials', 'Skin Polishing', 'Detan Treatments', 'Bridal Facials'], videoUrl: '/servicesVideo/skincare/Glow & Grace Skin Studio.mp4' },
  { id: 2, category: 'skincare', parlourName: 'True Beauty Skin Lounge', location: 'Koregaon Park, Pune', address: 'Lane 6, Koregaon Park, Near ABC Mall, Pune, Maharashtra 411001', phone: '+91 91234 56789', workingHours: '11:00 AM – 9:00 PM (Tue–Sun)', serviceName: 'Bridal Radiance Package', image: '/services/makeup/bridalMakeup.png', startingPrice: 3499, servicesOffered: ['Bridal Facials', 'Pre-bridal Packages', 'Body Polishing', 'Makeup Trials'], videoUrl: '/servicesVideo/skincare/True Beauty Skin Lounge.mp4' },
  { id: 3, category: 'makeup', parlourName: 'Blush & Blend Studio', location: 'Saket, New Delhi', address: '3rd Floor, Elegance Plaza, Saket District Centre, New Delhi 110017', phone: '+91 99888 77665', workingHours: '9:30 AM – 8:30 PM (Mon–Sat)', serviceName: 'Party Makeup & Styling', image: '/services/makeup/partyMakeup.png', startingPrice: 1999, servicesOffered: ['Party Makeup', 'Cocktail Makeup', 'Evening Look', 'Hair Styling'], videoUrl: '/servicesVideo/makeup/Blush & Blend Studio.mp4' },
  { id: 23, category: 'makeup', parlourName: 'Bridal Glow Studio', location: 'Jubilee Hills, Hyderabad', address: 'Road No. 14, Jubilee Hills, Hyderabad, Telangana 500033', phone: '+91 90123 66778', workingHours: '10:00 AM – 7:00 PM (Mon–Sat)', serviceName: 'Bridal Makeup & Trial', image: '/services/makeup/bridalMakeup.png', startingPrice: 4499, servicesOffered: ['Bridal Makeup', 'Pre-bridal Trial', 'Draping & Styling', 'Touch-up Kit'], serviceDescriptions: ['Full bridal makeup with premium products for your big day.', 'Trial session to finalise look and products before the wedding.', 'Saree and drape styling with professional draping.', 'Touch-up kit to keep you fresh through the events.'], videoUrl: '/servicesVideo/makeup/Bridal Glow Studio.mp4' },
  { id: 4, category: 'haircare', parlourName: 'Crown & Curls Salon', location: 'Banjara Hills, Hyderabad', address: 'Road No. 12, Banjara Hills, Opp. City Centre, Hyderabad, Telangana 500034', phone: '+91 90123 45678', workingHours: '10:00 AM – 9:00 PM (Mon–Sun)', serviceName: 'Keratin Smoothening Treatment', image: '/services/hairCare/hairTreatment.png', startingPrice: 2999, servicesOffered: ['Keratin Treatment', 'Smoothening', 'Hair Spa', 'Haircut & Styling'], videoUrl: '/servicesVideo/haircare/Crown & Curls Salon1.mp4' },
  { id: 5, category: 'wellness', parlourName: 'Serenity Spa & Wellness', location: 'MG Road, Bengaluru', address: '1st Floor, Lotus Towers, MG Road, Bengaluru, Karnataka 560001', phone: '+91 93030 11223', workingHours: '11:00 AM – 10:00 PM (All days)', serviceName: 'Aromatherapy Spa Ritual', image: '/services/wellness/spa.png', startingPrice: 2499, servicesOffered: ['Aromatherapy Massage', 'Body Spa', 'Head Massage', 'Detox Rituals'], videoUrl: '/servicesVideo/wellness/Serenityspa.mp4' },
  { id: 6, category: 'bath-body', parlourName: 'Bliss Bath & Body Studio', location: 'Jubilee Hills, Hyderabad', address: 'Plot 45, Jubilee Hills, Near Film Nagar, Hyderabad, Telangana 500033', phone: '+91 98480 55443', workingHours: '10:00 AM – 8:00 PM (Mon–Sat)', serviceName: 'Hair Spa & Scalp Treatment', image: '/services/bath&body/hairSpa.png', startingPrice: 1299, servicesOffered: ['Hair Spa', 'Scalp Massage', 'Aromatherapy Head Massage', 'Deep Conditioning'], videoUrl: '/servicesVideo/body&bath/Bliss Bath & Body Studio2.mp4' },
  { id: 7, category: 'haircare', parlourName: 'Crown & Curls Salon', location: 'Banjara Hills, Hyderabad', address: 'Road No. 12, Banjara Hills, Opp. City Centre, Hyderabad, Telangana 500034', phone: '+91 90123 45678', workingHours: '10:00 AM – 9:00 PM (Mon–Sun)', serviceName: 'Hair Smoothening Treatment', image: '/services/hairCare/hairSmoothening.png', startingPrice: 3499, servicesOffered: ['Keratin Smoothening', 'Brazilian Blowout', 'Chemical-Free Smoothening', 'Frizz Control'], videoUrl: '/servicesVideo/haircare/Crown & Curls Salon2.mp4' },
  { id: 8, category: 'haircare', parlourName: 'Locks & Layers Studio', location: 'Indiranagar, Bengaluru', address: '100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038', phone: '+91 98765 44321', workingHours: '10:00 AM – 8:00 PM (Mon–Sat)', serviceName: 'Hair Styling & Blow Dry', image: '/services/hairCare/hairStyle.png', startingPrice: 899, servicesOffered: ['Blow Dry', 'Hair Styling', 'Curls & Waves', 'Bridal Hair'], videoUrl: '/servicesVideo/haircare/Locks & Layers Studio.mp4' },
  { id: 9, category: 'haircare', parlourName: 'Serenity Hair Studio', location: 'Jubilee Hills, Hyderabad', address: 'Plot 78, Jubilee Hills, Hyderabad, Telangana 500033', phone: '+91 91234 09876', workingHours: '9:30 AM – 7:30 PM (Tue–Sun)', serviceName: 'Hair Spa & Scalp Treatment', image: '/services/hairCare/spaTreatment.png', startingPrice: 1499, servicesOffered: ['Hair Spa', 'Scalp Massage', 'Aromatherapy', 'Deep Conditioning'], videoUrl: '/servicesVideo/haircare/Serenity Hair Studio.mp4' },
  { id: 10, category: 'fragrance', parlourName: 'Scent Studio', location: 'Koramangala, Bengaluru', address: '80 Feet Road, Koramangala, Bengaluru, Karnataka 560034', phone: '+91 98765 11223', workingHours: '10:00 AM – 8:00 PM (Mon–Sat)', serviceName: 'Fragrance Consultation', image: '/services/fragrance/fragrance.png', startingPrice: 999, servicesOffered: ['Fragrance Profiling', 'Scent Recommendations', 'Layering Advice', 'Gift Curation'], videoUrl: '/servicesVideo/fragrance/Scent Studio.mp4' },
  { id: 11, category: 'fragrance', parlourName: 'Perfume Atelier', location: 'Bandra West, Mumbai', address: 'Linking Road, Bandra West, Mumbai, Maharashtra 400050', phone: '+91 99887 76543', workingHours: '11:00 AM – 9:00 PM (Tue–Sun)', serviceName: 'Perfume Testing & Sampling', image: '/services/fragrance/perfumeTesting.png', startingPrice: 499, servicesOffered: ['Perfume Sampling', 'Blind Testing', 'Comparison Sessions', 'Discovery Sets'], videoUrl: '/servicesVideo/fragrance/Perfume Atelier.mp4' },
  { id: 12, category: 'fragrance', parlourName: 'Bespoke Scents', location: 'Jubilee Hills, Hyderabad', address: 'Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033', phone: '+91 90111 22334', workingHours: '10:30 AM – 7:30 PM (Mon–Sat)', serviceName: 'Personalized Fragrance Creation', image: '/services/fragrance/personalized.png', startingPrice: 3499, servicesOffered: ['Custom Perfume Blending', 'Signature Scent Creation', 'Refill Service', 'Bottle Engraving'], videoUrl: '/servicesVideo/fragrance/Bespoke Scents.mp4' },
  { id: 13, category: 'wellness', parlourName: 'Glow Wellness Studio', location: 'Indiranagar, Bengaluru', address: '12th Main, Indiranagar, Bengaluru, Karnataka 560038', phone: '+91 98765 55443', workingHours: '10:00 AM – 7:00 PM (Mon–Sat)', serviceName: 'Skin & Wellness Consultation', image: '/services/wellness/skinWellness.png', startingPrice: 999, servicesOffered: ['Skin Analysis', 'Wellness Assessment', 'Diet & Lifestyle Tips', 'Product Recommendations'], videoUrl: '/servicesVideo/wellness/Glow Wellness.mp4' },
  { id: 14, category: 'gifting', parlourName: 'True Beauty Gifting Studio', location: 'Jubilee Hills, Hyderabad', address: 'Road No. 10, Jubilee Hills, Hyderabad, Telangana 500033', phone: '+91 90122 33445', workingHours: '10:00 AM – 7:00 PM (Mon–Sat)', serviceName: 'Beauty Gift Curation', image: '/services/gifting/beautyGift.png', startingPrice: 1999, servicesOffered: ['Gift Curation', 'Custom Gift Boxes', 'Wrapping & Personalisation', 'Delivery Arrangements'], videoUrl: '/servicesVideo/gifting/Gifting Studio.mp4' },
  { id: 15, category: 'gifting', parlourName: 'Luxe Gifting Co.', location: 'Bandra West, Mumbai', address: 'Linking Road, Bandra West, Mumbai, Maharashtra 400050', phone: '+91 99887 66554', workingHours: '11:00 AM – 8:00 PM (Tue–Sun)', serviceName: 'Luxury Gift Hamper Service', image: '/services/gifting/luxuryGift.png', startingPrice: 4999, servicesOffered: ['Luxury Hampers', 'Corporate Gifting', 'Premium Packaging', 'Nationwide Delivery'], videoUrl: '/servicesVideo/gifting/Luxe Gifting Co..mp4' },
  { id: 16, category: 'gifting', parlourName: 'Bespoke Gifts Studio', location: 'Koramangala, Bengaluru', address: '80 Feet Road, Koramangala, Bengaluru, Karnataka 560034', phone: '+91 98765 22334', workingHours: '10:00 AM – 6:00 PM (Mon–Sat)', serviceName: 'Personalized Gift Creation', image: '/services/gifting/personalizedGift.png', startingPrice: 3499, servicesOffered: ['Custom Gift Sets', 'Name Engraving', 'Message Cards', 'Theme-based Curation'], videoUrl: '/servicesVideo/gifting/Bespoke Gifts Studio.mp4' },
  { id: 17, category: 'jewellery', parlourName: 'Shine & Sparkle Jewellers', location: 'Jubilee Hills, Hyderabad', address: 'Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033', phone: '+91 90111 44556', workingHours: '10:00 AM – 7:00 PM (Mon–Sat)', serviceName: 'Bridal Jewellery Consultation', image: '/services/jewellery/bridalJewellery.png', startingPrice: 2999, servicesOffered: ['Bridal Set Curation', 'Trial & Styling', 'Custom Orders', 'Rental Options'], videoUrl: '/servicesVideo/jewellery/Shine & Sparkle Jewellers.mp4' },
  { id: 18, category: 'jewellery', parlourName: 'Pristine Jewellery Care', location: 'Bandra West, Mumbai', address: 'Linking Road, Bandra West, Mumbai, Maharashtra 400050', phone: '+91 99887 55443', workingHours: '11:00 AM – 6:00 PM (Tue–Sat)', serviceName: 'Jewellery Cleaning & Care', image: '/services/jewellery/jewelleryCleaning.png', startingPrice: 499, servicesOffered: ['Ultrasonic Cleaning', 'Polishing', 'Stone Checking', 'Minor Repairs'], videoUrl: '/servicesVideo/jewellery/Pristine Jewellery Care.mp4' },
  { id: 19, category: 'jewellery', parlourName: 'Style & Stone Studio', location: 'Indiranagar, Bengaluru', address: '100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038', phone: '+91 98765 33445', workingHours: '10:00 AM – 7:00 PM (Mon–Sat)', serviceName: 'Jewellery Styling Session', image: '/services/jewellery/jewelleryStyling.png', startingPrice: 999, servicesOffered: ['Outfit Pairing', 'Layering Advice', 'Occasion Styling', 'Photo Shoots'], videoUrl: '/servicesVideo/jewellery/Style & Stone Studio.mp4' },
  { id: 20, category: 'offers', parlourName: 'True Beauty Studio', location: 'Jubilee Hills, Hyderabad', address: 'Road No. 12, Jubilee Hills, Hyderabad, Telangana 500033', phone: '+91 90122 55667', workingHours: '10:00 AM – 8:00 PM (Mon–Sun)', serviceName: 'Beauty Service Package', image: '/services/offers/beautyService.png', startingPrice: 1499, servicesOffered: ['Facial & Cleanup', 'Manicure & Pedicure', 'Threading', 'Hair Styling'], videoUrl: '/servicesVideo/offers/True Beauty Studio.mp4' },
  { id: 21, category: 'offers', parlourName: 'Glow & Grace Salon', location: 'Bandra West, Mumbai', address: 'Linking Road, Bandra West, Mumbai, Maharashtra 400050', phone: '+91 99887 77665', workingHours: '11:00 AM – 8:00 PM (Tue–Sun)', serviceName: 'Beauty Treatment Combo', image: '/services/offers/beautyTreatment.png', startingPrice: 2499, servicesOffered: ['Hydra Facial', 'Body Massage', 'Hair Spa', 'Bridal Trial'], videoUrl: '/servicesVideo/offers/Glow & Grace Salon.mp4' },
  { id: 22, category: 'offers', parlourName: 'Serenity Beauty Lounge', location: 'Koramangala, Bengaluru', address: '80 Feet Road, Koramangala, Bengaluru, Karnataka 560034', phone: '+91 98765 44556', workingHours: '10:00 AM – 7:00 PM (Mon–Sat)', serviceName: 'Special Offer – Full Day Spa', image: '/services/offers/specialOffer.png', startingPrice: 3999, servicesOffered: ['Full Body Spa', 'Facial + Massage', 'Lunch included', 'Valid this month'], videoUrl: '/servicesVideo/offers/True Beauty Studio2.mp4' },
  { id: 25, category: 'bath-body', parlourName: 'Bliss Bath & Body Studio', location: 'Jubilee Hills, Hyderabad', address: 'Plot 45, Jubilee Hills, Near Film Nagar, Hyderabad, Telangana 500033', phone: '+91 98480 55443', workingHours: '10:00 AM – 8:00 PM (Mon–Sat)', serviceName: 'Hydra Facial & Glow', image: '/services/bath&body/hydraFacial.png', startingPrice: 1799, servicesOffered: ['Hydra Facial', 'Deep Cleansing', 'Mask & Serums', 'Relaxing Facial Massage'], videoUrl: '/servicesVideo/body&bath/Bliss Bath & Body Studio2 .mp4' },
];

export function getProductById(id: number | string) {
  const numId = typeof id === 'string' ? parseInt(id, 10) : id;
  return products.find((p) => p.id === numId) ?? null;
}

export function getProductsByCategory(categorySlug: string, subcategorySlug?: string): Product[] {
  let list = products.filter((p) => p.category === categorySlug);
  if (subcategorySlug) list = list.filter((p) => p.subcategory === subcategorySlug);
  return list;
}

export function getServicesByCategory(categorySlug?: string) {
  if (!categorySlug || categorySlug === 'all') {
    return beautyServices;
  }
  return beautyServices.filter((service) => service.category === categorySlug);
}

export function getServiceById(id: number | string): BeautyService | undefined {
  const numericId = typeof id === 'string' ? parseInt(id, 10) : id;
  if (Number.isNaN(numericId)) return undefined;
  return beautyServices.find((service) => service.id === numericId);
}
