export type CategoryItem = { id: number; name: string; slug: string; href: string };

export type Category = {
  id: number;
  name: string;
  slug: string;
  href: string;
  items: CategoryItem[];
};

export const categories: Category[] = [
  { id: 1, name: 'Skincare', slug: 'skincare', href: '/category/skincare', items: [{ id: 1, name: 'Face Wash & Cleansers', slug: 'cleansers', href: '/category/skincare/cleansers' }, { id: 2, name: 'Moisturizers', slug: 'moisturizers', href: '/category/skincare/moisturizers' }, { id: 3, name: 'Serums & Essences', slug: 'serums', href: '/category/skincare/serums' }, { id: 4, name: 'Sunscreen & SPF', slug: 'sunscreen', href: '/category/skincare/sunscreen' }, { id: 5, name: 'Toners & Mists', slug: 'toners', href: '/category/skincare/toners' }, { id: 6, name: 'Face Masks', slug: 'masks', href: '/category/skincare/masks' }, { id: 7, name: 'Eye Care', slug: 'eye-care', href: '/category/skincare/eye-care' }, { id: 8, name: 'Anti-Aging', slug: 'anti-aging', href: '/category/skincare/anti-aging' }] },
  { id: 2, name: 'Makeup', slug: 'makeup', href: '/category/makeup', items: [{ id: 1, name: 'Foundation & Concealer', slug: 'foundation', href: '/category/makeup/foundation' }, { id: 2, name: 'Lipstick & Lip Care', slug: 'lips', href: '/category/makeup/lips' }, { id: 3, name: 'Eyeshadow & Palettes', slug: 'eyes', href: '/category/makeup/eyes' }, { id: 4, name: 'Mascara & Eyeliners', slug: 'eye-makeup', href: '/category/makeup/eye-makeup' }, { id: 5, name: 'Blush & Highlighters', slug: 'cheeks', href: '/category/makeup/cheeks' }, { id: 6, name: 'Makeup Brushes', slug: 'brushes', href: '/category/makeup/brushes' }, { id: 7, name: 'Setting Sprays', slug: 'setting', href: '/category/makeup/setting' }, { id: 8, name: 'Makeup Removers', slug: 'removers', href: '/category/makeup/removers' }] },
  { id: 3, name: 'Bath & Body', slug: 'bath-body', href: '/category/bath-body', items: [{ id: 1, name: 'Body Wash & Soaps', slug: 'cleansers', href: '/category/bath-body/cleansers' }, { id: 2, name: 'Body Lotions & Creams', slug: 'moisturizers', href: '/category/bath-body/moisturizers' }, { id: 3, name: 'Body Scrubs & Exfoliants', slug: 'scrubs', href: '/category/bath-body/scrubs' }, { id: 4, name: 'Body Oils', slug: 'oils', href: '/category/bath-body/oils' }, { id: 5, name: 'Hand & Foot Care', slug: 'hand-foot', href: '/category/bath-body/hand-foot' }, { id: 6, name: 'Bath Bombs & Salts', slug: 'bath-accessories', href: '/category/bath-body/bath-accessories' }, { id: 7, name: 'Deodorants', slug: 'deodorants', href: '/category/bath-body/deodorants' }, { id: 8, name: 'Body Mists', slug: 'mists', href: '/category/bath-body/mists' }] },
  { id: 4, name: 'Haircare', slug: 'haircare', href: '/category/haircare', items: [{ id: 1, name: 'Shampoos', slug: 'shampoos', href: '/category/haircare/shampoos' }, { id: 2, name: 'Conditioners', slug: 'conditioners', href: '/category/haircare/conditioners' }, { id: 3, name: 'Hair Oils & Serums', slug: 'oils', href: '/category/haircare/oils' }, { id: 4, name: 'Hair Masks & Treatments', slug: 'masks', href: '/category/haircare/masks' }, { id: 5, name: 'Hair Styling Products', slug: 'styling', href: '/category/haircare/styling' }, { id: 6, name: 'Hair Accessories', slug: 'accessories', href: '/category/haircare/accessories' }, { id: 7, name: 'Scalp Care', slug: 'scalp', href: '/category/haircare/scalp' }, { id: 8, name: 'Hair Color', slug: 'color', href: '/category/haircare/color' }] },
  { id: 5, name: 'Fragrance', slug: 'fragrance', href: '/category/fragrance', items: [{ id: 1, name: 'Perfumes', slug: 'perfumes', href: '/category/fragrance/perfumes' }, { id: 2, name: 'Body Mists', slug: 'mists', href: '/category/fragrance/mists' }, { id: 3, name: 'Eau de Toilette', slug: 'edt', href: '/category/fragrance/edt' }, { id: 4, name: 'Eau de Parfum', slug: 'edp', href: '/category/fragrance/edp' }, { id: 5, name: 'Roll-On Perfumes', slug: 'roll-on', href: '/category/fragrance/roll-on' }, { id: 6, name: 'Fragrance Gift Sets', slug: 'gift-sets', href: '/category/fragrance/gift-sets' }, { id: 7, name: 'Scented Candles', slug: 'candles', href: '/category/fragrance/candles' }, { id: 8, name: 'Room Sprays', slug: 'room-sprays', href: '/category/fragrance/room-sprays' }] },
  { id: 6, name: 'Wellness', slug: 'wellness', href: '/category/wellness', items: [{ id: 1, name: 'Vitamins & Supplements', slug: 'vitamins', href: '/category/wellness/vitamins' }, { id: 2, name: 'Hair & Skin Gummies', slug: 'gummies', href: '/category/wellness/gummies' }, { id: 3, name: 'Wellness Kits', slug: 'kits', href: '/category/wellness/kits' }, { id: 4, name: 'Ayurvedic Products', slug: 'ayurvedic', href: '/category/wellness/ayurvedic' }, { id: 5, name: 'Herbal Teas', slug: 'teas', href: '/category/wellness/teas' }, { id: 6, name: 'Self-Care Essentials', slug: 'self-care', href: '/category/wellness/self-care' }, { id: 7, name: 'Wellness Accessories', slug: 'accessories', href: '/category/wellness/accessories' }, { id: 8, name: 'Gift Sets', slug: 'gift-sets', href: '/category/wellness/gift-sets' }] },
  { id: 7, name: 'Gifting', slug: 'gifting', href: '/category/gifting', items: [{ id: 1, name: 'Skincare Gift Sets', slug: 'skincare-sets', href: '/category/gifting/skincare-sets' }, { id: 2, name: 'Makeup Gift Sets', slug: 'makeup-sets', href: '/category/gifting/makeup-sets' }, { id: 3, name: 'Luxury Gift Boxes', slug: 'luxury-boxes', href: '/category/gifting/luxury-boxes' }, { id: 4, name: 'Personalized Gifts', slug: 'personalized', href: '/category/gifting/personalized' }, { id: 5, name: 'Holiday Collections', slug: 'holiday', href: '/category/gifting/holiday' }, { id: 6, name: 'Gift Cards', slug: 'gift-cards', href: '/category/gifting/gift-cards' }, { id: 7, name: 'Corporate Gifting', slug: 'corporate', href: '/category/gifting/corporate' }, { id: 8, name: 'Wedding Favors', slug: 'wedding', href: '/category/gifting/wedding' }] },
  { id: 8, name: 'Jewellery', slug: 'jewellery', href: '/category/jewellery', items: [{ id: 1, name: 'Earrings', slug: 'earrings', href: '/category/jewellery/earrings' }, { id: 2, name: 'Necklaces', slug: 'necklaces', href: '/category/jewellery/necklaces' }, { id: 3, name: 'Rings', slug: 'rings', href: '/category/jewellery/rings' }, { id: 4, name: 'Bracelets', slug: 'bracelets', href: '/category/jewellery/bracelets' }, { id: 5, name: 'Pendants', slug: 'pendants', href: '/category/jewellery/pendants' }] },
  { id: 9, name: 'Offers', slug: 'offers', href: '/offers', items: [{ id: 1, name: 'Flash Sales', slug: 'flash-sales', href: '/offers/flash-sales' }, { id: 2, name: 'Buy 1 Get 1', slug: 'bogo', href: '/offers/bogo' }, { id: 3, name: 'New Arrivals Sale', slug: 'new-arrivals', href: '/offers/new-arrivals' }, { id: 4, name: 'Clearance Sale', slug: 'clearance', href: '/offers/clearance' }, { id: 5, name: 'Combo Offers', slug: 'combo', href: '/offers/combo' }, { id: 6, name: 'Seasonal Sales', slug: 'seasonal', href: '/offers/seasonal' }, { id: 7, name: 'Member Exclusive', slug: 'member-exclusive', href: '/offers/member-exclusive' }, { id: 8, name: 'Bundle Deals', slug: 'bundles', href: '/offers/bundles' }] }
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getCategoryNameBySlug(slug: string): string {
  const cat = getCategoryBySlug(slug);
  return cat ? cat.name : slug;
}
